#!/bin/bash
##--------------------------------------------------------------------------------
##
##   ▞▀▖▛▀▖▞▀▖▛▀▖        ▌      Created....: © Destroyer 2025
##   ▌  ▙▄▘▌  ▙▄▘▞▀▖▝▀▖▞▀▌▌ ▌   Description: Toolchain for Amstrad CPC.
##   ▌ ▖▌  ▌ ▖▌▚ ▛▀ ▞▀▌▌ ▌▚▄▌   Github.....: https://github.com/CPCReady
##   ▝▀ ▘  ▝▀ ▘ ▘▝▀▘▝▀▘▝▀▘▗▄▘   Doc........: https://cpcready.readthedocs.io/  
##
##-----------------------------LICENSE NOTICE--------------------------------------
##  This file is part of CPCReady Basic programation.
##  Copyright (C) 2025 Destroyer
##
##  This program is free software: you can redistribute it and/or modify
##  it under the terms of the GNU Lesser General Public License as published by
##  the Free Software Foundation, either version 3 of the License, or
##  (at your option) any later version.
##
##  This program is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##  GNU Lesser General Public License for more details.
##
##  You should have received a copy of the GNU Lesser General Public License
##  along with this program.  If not, see <http://www.gnu.org/licenses/>.
##--------------------------------------------------------------------------------

  # Load environment variables
  if [[ -f ".dev" ]]; then
      source ".dev"
      CPCREADY_LIB="$CPCREADY_DIR/lib/cpc-common.sh"
      source "$CPCREADY_LIB"
      echo
      __cpcready_echo_yellow "******* DEV ENVIRONMENT *******"
      echo
  else
      CPCREADY_DIR="$(brew --prefix)/opt/cpcready-tools"
      CPCREADY_LIB="$(brew --prefix)/opt/cpcready-tools/lib/cpc-common.sh"
      source "$CPCREADY_LIB"
      # CPCREADY_DIR="/Users/destroyer/PROJECTS/CPCReady3/toolchain/tools/scripts"
      # CPCREADY_LIB="$CPCREADY_DIR/lib/cpc-common.sh"
      # source "$CPCREADY_LIB"
      echo
  fi

  COMMAND="$1"
    # Remueve el primer argumento para pasar el resto solo si hay argumentos
    if [ "$#" -gt 0 ]; then
      shift
    fi

  # Usa una estructura 'case' para redirigir a los scripts correctos
  case "$COMMAND" in
    ""|-h|--help)
      __cpcready_logo
      usage
      exit 0
      ;;
    -v|--version)
      __cpcready_logo
      echo "v$VERSION"
      exit 0
      ;;
    "save")
      source "$CPCREADY_DIR/lib/cpc-save.sh" "$@"
      ;;
    "run")
      source "$CPCREADY_DIR/lib/cpc-run.sh" "$@"
      ;;
    "disc")
      source "$CPCREADY_DIR/lib/cpc-disc.sh" "$@"
      ;;
    "version")
      source "$CPCREADY_DIR/lib/cpc-version.sh" "$@"
      ;;
    "init")
      source "$CPCREADY_DIR/lib/cpc-init.sh" "$@"
      ;;
    "logo")
      source "$CPCREADY_DIR/ec/logo.sh"
      ;;
    "commands")
      source "$CPCREADY_LIB/cpc-commands.sh" "$@"
      ;;  
    *)
      __cpcready_logo
      __cpcready_echo_red "Error: Unknown command:$COMMAND"
      usage
      exit 1
      ;;
  esac
